# Generated by Django 4.1.5 on 2023-01-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0003_issue_assigned_to_alter_issue_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assigned_to",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Assignee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
