# Generated by Django 4.1.5 on 2023-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_alter_issue_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="added_files",
            field=models.FileField(null=True, upload_to="", verbose_name="files"),
        ),
    ]
