# Generated by Django 4.1.5 on 2023-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_alter_comment_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="added_files",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="files"
            ),
        ),
    ]
