# Generated by Django 4.1.5 on 2023-01-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0008_rename_issue_comment_related_issue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["date_created"]},
        ),
    ]
