# Generated by Django 4.1.5 on 2023-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_alter_issue_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={},
        ),
        migrations.AddField(
            model_name="issue",
            name="added_files",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="files"
            ),
        ),
    ]
