# Generated by Django 4.1.5 on 2023-01-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_alter_comment_related_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="related_issue",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.issue",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.TextField(
                choices=[
                    ("New", "New"),
                    ("On Hold", "On Hold"),
                    ("Waiting", "Waiting"),
                    ("Canceled", "Canceled"),
                    ("Resolved", "Resolved"),
                    ("In Development", "In Development"),
                ],
                default="New",
            ),
        ),
    ]
