# Generated by Django 4.1.5 on 2023-01-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0012_alter_comment_related_issue_alter_issue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="related_issue",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="issues.issue",
            ),
        ),
    ]
